# Generated by Django 3.2.4 on 2021-06-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('nom_cliente', models.CharField(max_length=25)),
                ('usuario', models.CharField(max_length=25)),
                ('correo', models.TextField(max_length=35)),
                ('f_nacimiento', models.DateField()),
                ('contraseña', models.TextField(max_length=35)),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
