# Generated by Django 3.2.4 on 2021-06-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0002_auto_20210625_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='f_nacimiento',
            new_name='fnacimiento',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nom_cliente',
            new_name='nomCliente',
        ),
    ]
