# Generated by Django 3.2.4 on 2021-06-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0003_auto_20210625_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
    ]
