# Generated by Django 3.2.4 on 2021-06-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0005_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='pyme',
            fields=[
                ('NomPyme', models.CharField(max_length=25)),
                ('rutempresa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direccion', models.TextField(max_length=35)),
                ('rutpersona', models.CharField(max_length=10)),
                ('nomDueño', models.CharField(max_length=25)),
                ('categpyme', models.CharField(max_length=25)),
                ('horario', models.TextField(max_length=35)),
                ('telefono', models.TextField(max_length=35)),
            ],
        ),
    ]
