# Generated by Django 3.2.4 on 2021-06-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0006_pyme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyme',
            name='direccion',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='horario',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='telefono',
            field=models.CharField(max_length=25),
        ),
    ]
