# Generated by Django 3.2.4 on 2021-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0007_auto_20210626_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nomCategoria',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomCliente',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='NomPyme',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='nomDueño',
            field=models.CharField(max_length=60),
        ),
    ]
