# Generated by Django 3.2.4 on 2021-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oracle', '0008_auto_20210626_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientePyme',
            fields=[
                ('nomCliente', models.CharField(max_length=25)),
                ('apellcliente', models.CharField(max_length=25)),
                ('usuario', models.CharField(max_length=25)),
                ('correo', models.TextField(max_length=40)),
                ('fnacimiento', models.DateField()),
                ('contraseña', models.TextField(max_length=35)),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='usuarioApp',
            fields=[
                ('nomuser', models.CharField(max_length=25)),
                ('apelluser', models.CharField(max_length=25)),
                ('usuario', models.CharField(max_length=25)),
                ('correo', models.TextField(max_length=40)),
                ('fnacimiento', models.DateField()),
                ('contraseña', models.TextField(max_length=35)),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
